# Deep Linking Test
# Tests deep link handling and navigation

appId: ${APP_ID}
name: Deep Linking
tags:
  - deeplink
  - navigation

---

# Test opening app via deep link
- launchApp:
    clearState: true
    url: "yourapp://home"

- assertVisible: ".*"
- takeScreenshot: screenshots/deeplink-home

# Test deep link to specific screen
- launchApp:
    url: "yourapp://profile/123"
    
- assertVisible: ".*"
- takeScreenshot: screenshots/deeplink-profile

# Test deep link with parameters
- launchApp:
    url: "yourapp://search?query=test&filter=active"
    
- assertVisible: ".*"
# - assertVisible: "test"
- takeScreenshot: screenshots/deeplink-search

# Test invalid deep link handling
- launchApp:
    url: "yourapp://invalid-route"
    
- assertVisible: ".*"
# Should fallback to home or show error
- takeScreenshot: screenshots/deeplink-invalid
