# App Launch and Basic Navigation Test
# This flow tests that the app launches successfully and basic navigation works

appId: ${APP_ID}
name: App Launch and Navigation
tags:
  - smoke
  - critical

---

# Launch the app
- launchApp

# Wait for app to load (adjust timeout as needed)
- assertVisible: ".*"

# Take a screenshot for documentation
- takeScreenshot: screenshots/app-launch

# Optional: Check if welcome screen or main screen appears
# Uncomment and adjust based on your app's structure
# - assertVisible: "Welcome"
# - assertVisible: "Home"

# Test basic navigation (adjust selectors based on your app)
# Example: Tap on a tab or button
# - tapOn: "Settings"
# - assertVisible: "Settings Screen"
# - takeScreenshot: screenshots/settings-screen

# Go back to home
# - back

# Final assertion
# - assertVisible: "Home"

- takeScreenshot: screenshots/navigation-complete
