# Helper: Background and Foreground App
# Reusable flow for testing app state transitions

---

# Put app in background
- pressKey: Home

# Wait for a few seconds
- wait: 2000

# Bring app back to foreground
- launchApp

# Wait for app to resume
- waitForAnimationToEnd

# Verify app state is maintained
- assertVisible: ".*"
