# Network and Data Loading Test
# Tests app behavior with network requests and loading states

appId: ${APP_ID}
name: Network and Data Loading
tags:
  - network
  - api

---

- launchApp:
    clearState: true

# Wait for initial data load
- assertVisible: ".*"

# Test loading state (if visible)
# - assertVisible: "Loading|Spinner"

# Wait for content to appear
- waitForAnimationToEnd:
    timeout: 10000

# Assert data loaded successfully
# - assertVisible: ".*Content.*"

- takeScreenshot: screenshots/data-loaded

# Test refresh functionality
- scroll:
    direction: UP
    speed: 100

- waitForAnimationToEnd:
    timeout: 5000

# Navigate to a screen that requires data fetching
# - tapOn: "Details|More"
# - waitForAnimationToEnd
# - assertVisible: ".*"

# Test offline behavior (requires manual network toggle or mock)
# Note: Maestro doesn't natively support network toggling
# You may need to use device settings or mock APIs

- takeScreenshot: screenshots/network-complete
