# User Authentication Flow Test
# Tests login/signup functionality

appId: ${APP_ID}
name: User Authentication
tags:
  - auth
  - critical

---

- launchApp:
    clearState: true  # Start with fresh app state

# Wait for app to load
- assertVisible: ".*"

# Navigate to login screen (adjust based on your app)
# - tapOn: "Login"
# - assertVisible: "Email"
# - assertVisible: "Password"

# Test with invalid credentials first
# - tapOn: "Email"
# - inputText: "invalid@test.com"
# - tapOn: "Password"
# - inputText: "wrongpass"
# - tapOn: "Login Button"
# - assertVisible: "Error|Invalid"

# Test with valid credentials
# - tapOn: "Email"
# - clearTextField
# - inputText: ${TEST_EMAIL}
# - tapOn: "Password"
# - clearTextField
# - inputText: ${TEST_PASSWORD}
# - tapOn: "Login Button"

# Wait for successful login
# - assertVisible: "Welcome|Dashboard|Home"

- takeScreenshot: screenshots/auth-complete

# Optional: Test logout
# - tapOn: "Profile|Settings"
# - tapOn: "Logout"
# - assertVisible: "Login"
