# Cross-Platform Compatibility Test
# Tests app behavior across iOS and Android

appId: ${APP_ID}
name: Cross-Platform Compatibility
tags:
  - compatibility
  - cross-platform

---

- launchApp

# Platform-specific checks
- runScript:
    when: platform == 'iOS'
    script: |
      echo "Running iOS-specific tests"

- runScript:
    when: platform == 'Android'
    script: |
      echo "Running Android-specific tests"

# Test common UI elements
- assertVisible: ".*"

# Platform-specific navigation patterns
# iOS: Bottom tab bar
# Android: Bottom navigation or drawer

# Test back button behavior
# Android has hardware back button
# iOS uses gesture or in-app back button

- takeScreenshot: screenshots/platform-initial

# Test platform-specific gestures
# iOS: Swipe from left edge to go back
# Android: Use system back button

# Test keyboard behavior
# - tapOn: "Search"
# - inputText: "test"
# - assertVisible: "test"

# iOS: Check for keyboard accessory view
# Android: Check for keyboard actions

# Test date/time pickers (different on each platform)
# - tapOn: "Select Date"
# Platform will show native picker

# Test share functionality (different on each platform)
# - tapOn: "Share"
# Native share sheet should appear

- takeScreenshot: screenshots/platform-complete
