# Helper: Login Flow
# Reusable flow for logging into the app

---

# Navigate to login screen (if not already there)
# - tapOn: "Login|Sign In"

# Enter credentials
# - tapOn: "Email"
# - inputText: ${TEST_EMAIL}
# - tapOn: "Password"
# - inputText: ${TEST_PASSWORD}

# Submit login
# - tapOn: "Login Button|Sign In Button"

# Wait for successful login
# - waitForAnimationToEnd
# - assertVisible: "Home|Dashboard"
